__autogen__ = (
    """
    mkinit ~/code/magnet-sys-exploratory/magnet/__init__.py --lazy-loader -w
    """)

# Manually declare what should be exposed when regenerating with mkinit
__submodules__ = {
    'helm_outputs': ['HelmOutputs'],
    'example_random_predictor': [],
    'demo': [],
    'loaders': [],
    'predictor': [],
    'utils': [],
}

# Autogenerated code that actually exposes the requrested modules / attributes

import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'demo',
        'example_random_predictor',
        'helm_outputs',
        'loaders',
        'predictor',
        'utils',
    },
    submod_attrs={
        'helm_outputs': [
            'HelmOutputs',
        ],
    },
)

__all__ = ['HelmOutputs', 'demo', 'example_random_predictor', 'helm_outputs',
           'loaders', 'predictor', 'utils']
