__autogen__ = (
    """
    mkinit ~/code/magnet-sys-exploratory/magnet/__init__.py -w --lazy-loader --noattrs
    """)

# Autogenerated

import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'demo',
        'example_random_predictor',
        'helm_outputs',
        'loaders',
        'predictor',
    },
    submod_attrs={},
)

__all__ = ['demo', 'example_random_predictor', 'helm_outputs', 'loaders',
           'predictor']
