# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# Based on ~/code/xcookie/xcookie/rc/tests.yml.in
# Now based on ~/code/xcookie/xcookie/builders/github_actions.py
# See: https://github.com/Erotemic/xcookie

name: PurePyCI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build_and_test_sdist:
    ##
    # Build the pure python package from source and test it in the
    # same environment.
    ##
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4.2.2
    - name: Set up Python 3.13
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.13'
    - name: Upgrade pip
      run: |-
        python -m pip install pip uv -U
        python -m uv pip install -r pyproject.toml --extra tests
    - name: Build sdist
      shell: bash
      run: |-
        python -m pip install pip uv -U
        python -m uv pip install setuptools>=0.8 wheel build twine
        python -m build --sdist --outdir wheelhouse
        python -m twine check ./wheelhouse/aiq_magnet*.tar.gz
    - name: Install sdist
      run: |-
        ls -al wheelhouse
        python -m uv pip install wheelhouse/aiq_magnet*.tar.gz -v
    - name: Test minimal loose sdist
      env: {}
      run: |-
        pwd
        ls -al
        # Run in a sandboxed directory
        WORKSPACE_DNAME="testsrcdir_minimal_${CI_PYTHON_VERSION}_${GITHUB_RUN_ID}_${RUNNER_OS}"
        mkdir -p $WORKSPACE_DNAME
        cd $WORKSPACE_DNAME
        # Run the tests
        # Get path to installed package
        MOD_DPATH=$(python -c "import magnet, os; print(os.path.dirname(magnet.__file__))")
        echo "MOD_DPATH = $MOD_DPATH"
        python -m pytest --verbose --cov=magnet $MOD_DPATH ../tests
        cd ..
    - name: Test full loose sdist
      env: {}
      run: |-
        pwd
        ls -al
        true
        # Run in a sandboxed directory
        WORKSPACE_DNAME="testsrcdir_full_${CI_PYTHON_VERSION}_${GITHUB_RUN_ID}_${RUNNER_OS}"
        mkdir -p $WORKSPACE_DNAME
        cd $WORKSPACE_DNAME
        # Run the tests
        # Get path to installed package
        MOD_DPATH=$(python -c "import magnet, os; print(os.path.dirname(magnet.__file__))")
        echo "MOD_DPATH = $MOD_DPATH"
        python -m pytest --verbose --cov=magnet $MOD_DPATH ../tests
        cd ..
    - uses: actions/upload-artifact@v4.4.0
      name: Upload sdist artifact
      with:
        name: sdist_wheels
        path: ./wheelhouse/aiq_magnet*.tar.gz
  build_purepy_wheels:
    ##
    # Download and test the pure-python wheels that were build in the
    # build_purepy_wheels and test them in this independent environment.
    ##
    name: ${{ matrix.python-version }} on ${{ matrix.os }}, arch=${{ matrix.arch }} with ${{ matrix.install-extras }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.13'
        arch:
        - auto
    steps:
    - name: Checkout source
      uses: actions/checkout@v4.2.2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
      if: runner.os == 'Linux' && matrix.arch != 'auto'
      with:
        platforms: all
    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build pure wheel
      shell: bash
      run: |-
        python -m pip install pip uv -U
        python -m uv pip install setuptools>=0.8 wheel build twine
        python -m build --wheel --outdir wheelhouse
        python -m twine check ./wheelhouse/aiq_magnet*.whl
    - name: Show built files
      shell: bash
      run: ls -la wheelhouse
    - uses: actions/upload-artifact@v4.4.0
      name: Upload wheels artifact
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.arch }}
        path: ./wheelhouse/aiq_magnet*.whl
  test_purepy_wheels:
    name: ${{ matrix.python-version }} on ${{ matrix.os }}, arch=${{ matrix.arch }} with ${{ matrix.install-extras }}
    if: "! startsWith(github.event.ref, 'refs/heads/release')"
    runs-on: ${{ matrix.os }}
    needs:
    - build_purepy_wheels
    strategy:
      fail-fast: false
      matrix:
        # Xcookie generates an explicit list of environments that will be used
        # for testing instead of using the more concise matrix notation.
        include:
        - python-version: '3.13'
          install-extras: tests,optional
          os: ubuntu-latest
          arch: auto
          uv-resolution: lowest-direct
        - python-version: '3.11'
          install-extras: tests,optional
          os: ubuntu-latest
          arch: auto
          uv-resolution: highest
        - python-version: '3.12'
          install-extras: tests,optional
          os: ubuntu-latest
          arch: auto
          uv-resolution: highest
        - python-version: '3.13'
          install-extras: tests,optional
          os: ubuntu-latest
          arch: auto
          uv-resolution: highest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4.2.2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
      if: runner.os == 'Linux' && matrix.arch != 'auto'
      with:
        platforms: all
    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/download-artifact@v4.1.8
      name: Download wheels
      with:
        pattern: wheels-*
        merge-multiple: true
        path: wheelhouse
    - name: Install wheel ${{ matrix.install-extras }}
      shell: bash
      env:
        INSTALL_EXTRAS: ${{ matrix.install-extras }}
        UV_RESOLUTION: ${{ matrix.uv-resolution }}
      run: |-
        echo "Finding the path to the wheel"
        ls wheelhouse || echo "wheelhouse does not exist"
        echo "Installing helpers: update pip"
        python -m pip install pip uv -U
        echo "Installing helpers: setuptools"
        python -m uv pip install --resolution=highest setuptools>=0.8 setuptools_scm wheel build -U
        echo "Installing helpers: tomli and pkginfo"
        python -m uv pip install --resolution=highest tomli pkginfo
        export WHEEL_FPATH=$(python -c "if 1:
            import pathlib
            dist_dpath = pathlib.Path('wheelhouse')
            candidates = list(dist_dpath.glob('aiq_magnet*.whl'))
            candidates += list(dist_dpath.glob('aiq_magnet*.tar.gz'))
            fpath = sorted(candidates)[-1]
            print(str(fpath).replace(chr(92), chr(47)))
        ")
        export MOD_VERSION=$(python -c "if 1:
            from pkginfo import Wheel, SDist
            import pathlib
            fpath = '$WHEEL_FPATH'
            cls = Wheel if fpath.endswith('.whl') else SDist
            item = cls(fpath)
            print(item.version)
        ")
        echo "WHEEL_FPATH=$WHEEL_FPATH"
        echo "INSTALL_EXTRAS=$INSTALL_EXTRAS"
        echo "UV_RESOLUTION=$UV_RESOLUTION"
        echo "MOD_VERSION=$MOD_VERSION"
        python -m uv pip install --prerelease=allow "aiq-magnet[$INSTALL_EXTRAS]==$MOD_VERSION" -f wheelhouse
        echo "Install finished."
    - name: Test wheel ${{ matrix.install-extras }}
      shell: bash
      env:
        CI_PYTHON_VERSION: py${{ matrix.python-version }}
      run: |-
        echo "Creating test sandbox directory"
        export WORKSPACE_DNAME="testdir_${CI_PYTHON_VERSION}_${GITHUB_RUN_ID}_${RUNNER_OS}"
        echo "WORKSPACE_DNAME=$WORKSPACE_DNAME"
        mkdir -p $WORKSPACE_DNAME
        echo "cd-ing into the workspace"
        cd $WORKSPACE_DNAME
        pwd
        ls -altr
        # Get the path to the installed package and run the tests
        export MOD_DPATH=$(python -c "import magnet, os; print(os.path.dirname(magnet.__file__))")
        export MOD_NAME=magnet
        echo "
        ---
        MOD_DPATH = $MOD_DPATH
        ---
        running the pytest command inside the workspace
        ---
        "
        python -m pytest --verbose -p pytester -p no:doctest --xdoctest --cov-config ../pyproject.toml --cov-report term --durations=100 --cov="$MOD_NAME" "$MOD_DPATH" ../tests
        echo "pytest command finished, moving the coverage file to the repo root"
        ls -al
        # Move coverage file to a new name
        mv .coverage "../.coverage.$WORKSPACE_DNAME"
        echo "changing directory back to th repo root"
        cd ..
        ls -al
    - name: Combine coverage Linux
      if: runner.os == 'Linux'
      run: |-
        echo '############ PWD'
        pwd
        cp .wheelhouse/.coverage* . || true
        ls -al
        uv pip install coverage[toml] | pip install coverage[toml]
        echo '############ combine'
        coverage combine . || true
        echo '############ XML'
        coverage xml -o ./coverage.xml || true
        echo '### The cwd should now have a coverage.xml'
        ls -altr
        pwd
    - uses: codecov/codecov-action@v5.4.3
      name: Codecov Upload
      with:
        file: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
  test_deploy:
    name: Deploy Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && ! startsWith(github.event.ref, 'refs/tags') && ! startsWith(github.event.ref, 'refs/heads/release')
    needs:
    - build_and_test_sdist
    - build_purepy_wheels
    steps:
    - name: Checkout source
      uses: actions/checkout@v4.2.2
    - uses: actions/download-artifact@v4.1.8
      name: Download wheels
      with:
        pattern: wheels-*
        merge-multiple: true
        path: wheelhouse
    - uses: actions/download-artifact@v4.1.8
      name: Download sdist
      with:
        name: sdist_wheels
        path: wheelhouse
    - name: Show files to upload
      shell: bash
      run: ls -la wheelhouse
    - uses: actions/upload-artifact@v4.4.0
      name: Upload deploy artifacts
      with:
        name: deploy_artifacts
        path: |-
          wheelhouse/*.whl
          wheelhouse/*.zip
          wheelhouse/*.tar.gz
  live_deploy:
    name: Deploy Live
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags') || startsWith(github.event.ref, 'refs/heads/release'))
    needs:
    - build_and_test_sdist
    - build_purepy_wheels
    steps:
    - name: Checkout source
      uses: actions/checkout@v4.2.2
    - uses: actions/download-artifact@v4.1.8
      name: Download wheels
      with:
        pattern: wheels-*
        merge-multiple: true
        path: wheelhouse
    - uses: actions/download-artifact@v4.1.8
      name: Download sdist
      with:
        name: sdist_wheels
        path: wheelhouse
    - name: Show files to upload
      shell: bash
      run: ls -la wheelhouse
    - uses: actions/upload-artifact@v4.4.0
      name: Upload deploy artifacts
      with:
        name: deploy_artifacts
        path: |-
          wheelhouse/*.whl
          wheelhouse/*.zip
          wheelhouse/*.tar.gz
  release:
    name: Create Github Release
    if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags') || startsWith(github.event.ref, 'refs/heads/release'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
    - live_deploy
    steps:
    - name: Checkout source
      uses: actions/checkout@v4.2.2
    - uses: actions/download-artifact@v4.1.8
      name: Download artifacts
      with:
        name: deploy_artifacts
        path: wheelhouse
    - name: Show files to release
      shell: bash
      run: ls -la wheelhouse
    - run: 'echo "Automatic Release Notes. TODO: improve" > ${{ github.workspace }}-CHANGELOG.txt'
    - name: Tag Release Commit
      if: (startsWith(github.event.ref, 'refs/heads/release'))
      run: |-
        export VERSION=$(python -c "import setup; print(setup.VERSION)")
        git tag "v$VERSION"
        git push origin "v$VERSION"
    - uses: softprops/action-gh-release@v1
      name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: Automatic Release
        generate_release_notes: true
        draft: true
        prerelease: false
        files: |-
          wheelhouse/*.whl
          wheelhouse/*.asc
          wheelhouse/*.ots
          wheelhouse/*.zip
          wheelhouse/*.tar.gz


